const EnvConfig = {
  CLIENTID: process.env.REACT_APP_CLIENT_ID,
  CLIENTSECRET: process.env.REACT_APP_CLIENT_SECRET,
  REDIRECTURL: process.env.REACT_APP_REDIRECT_URI,
  CODEPOSTURL: process.env.REACT_APP_URL_CODE_POST_URL,
  WRITEPOSTURL: process.env.REACT_APP_WRITE_POST_URL,
  IMGPOSTURL: process.env.REACT_APP_IMG_POST_URL,
  GETHISTORY: process.env.REACT_APP_GET_HISTORY
};

export default EnvConfig;
