export { default as X } from "./X";
export { default as LoginLogo } from "./LoginLogo";
export { default as GAuthLogo } from "./GAuthLogo";
export { default as School } from "./School";
export { default as Etc } from "./Etc";
export { default as Logo } from "./Logo";
export { default as Notice } from "./Notice";
export { default as NotFound } from "./NotFound";
export { default as Arrow } from "./Arrow";
export { default as SchoolSong } from "./SchoolSong";
export { default as ScrollButton } from "./ScrollButton";
export { default as H1Icon } from "./H1Icon";
export { default as H2Icon } from "./H2Icon";
export { default as H3Icon } from "./H3Icon";
export { default as H4Icon } from "./H4Icon";
export { default as DivideLineIcon} from "./DivideLineIcon";
export { default as BoldIcon} from "./BoldIcon";
export { default as InclineIcon} from "./InclineIcon";
export { default as DrawIcon } from "./DrawIcon";
export { default as QuoteIcon } from "./QuoteIcon";
export { default as LinkIcon } from "./LinkIcon";
export { default as CodeIcon } from "./CodeIcon";