export { default as X } from "./X";
export { default as LoginLogo } from "./LoginLogo";
export { default as GAuthLogo } from "./GAuthLogo";
export { default as School } from "./School";
export { default as Etc } from "./Etc";
export { default as Logo } from "./Logo";
export { default as Notice } from "./Notice";
export { default as NotFound } from "./NotFound";
export { default as Arrow } from "./Arrow";
